name: 
  piawka
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bash=5.2.37=h4be8908_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - curl=7.71.1=he644dc0_8
  - gawk=5.3.1=hcd3d067_0
  - gmp=6.3.0=hac33072_2
  - htslib=1.9=ha228f0b_7
  - krb5=1.17.2=h926e7f8_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libcurl=7.71.1=hcdd3856_8
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libnghttp2=1.41.0=hab1572f_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libzlib=1.2.13=h4ab18f5_6
  - mpfr=4.2.1=h90cbb55_3
  - ncurses=6.5=h2d0b736_3
  - openssl=1.1.1w=hd590300_0
  - piawka=0.8.11=hdfd78af_0
  - readline=8.3=h853b02a_0
  - tabix=1.11=hdfd78af_0
  - tk=8.6.13=noxft_h4845f30_101
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
prefix: 
  /cfs/klemming/projects/snic/snic2020-6-222/Projects/Tconura/working/Andre/bin/miniforge3/envs/piawka
