name: 
  r-arena
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.14.1=h332b0f4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - harfbuzz=11.5.0=h15599e2_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.1.0=h767d61c_5
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=14.2.0=hed042b8_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.3=h26f9b46_0
  - pandoc=3.6.4=ha770c72_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - r-askpass=1.2.1=r45h54b55ab_1
  - r-assertthat=0.2.1=r45hc72bb7e_6
  - r-backports=1.5.0=r45h54b55ab_2
  - r-base=4.5.1=h14df4e6_3
  - r-base64enc=0.1_3=r45h54b55ab_1008
  - r-bit=4.6.0=r45h54b55ab_1
  - r-bit64=4.6.0_1=r45h54b55ab_1
  - r-blob=1.2.4=r45hc72bb7e_3
  - r-broom=1.0.10=r45hc72bb7e_0
  - r-bslib=0.9.0=r45hc72bb7e_1
  - r-cachem=1.1.0=r45h54b55ab_2
  - r-callr=3.7.6=r45hc72bb7e_2
  - r-cellranger=1.1.0=r45hc72bb7e_1008
  - r-cli=3.6.5=r45h3697838_1
  - r-clipr=0.8.0=r45hc72bb7e_4
  - r-colorspace=2.1_1=r45h54b55ab_1
  - r-conflicted=1.2.0=r45h785f33e_3
  - r-cowplot=1.2.0=r45hc72bb7e_2
  - r-cpp11=0.5.2=r45h785f33e_2
  - r-crayon=1.5.3=r45hc72bb7e_2
  - r-curl=7.0.0=r45h10955f1_1
  - r-data.table=1.17.8=r45h1c8cec4_1
  - r-dbi=1.2.3=r45hc72bb7e_2
  - r-dbplyr=2.5.1=r45hc72bb7e_1
  - r-digest=0.6.37=r45h3697838_1
  - r-dplyr=1.1.4=r45h3697838_2
  - r-dtplyr=1.3.2=r45hc72bb7e_1
  - r-ellipsis=0.3.2=r45h54b55ab_4
  - r-evaluate=1.0.5=r45hc72bb7e_1
  - r-fansi=1.0.6=r45h54b55ab_2
  - r-farver=2.1.2=r45h3697838_2
  - r-fastmap=1.2.0=r45h3697838_2
  - r-fontawesome=0.5.3=r45hc72bb7e_1
  - r-forcats=1.0.0=r45hc72bb7e_3
  - r-fs=1.6.6=r45h3697838_1
  - r-gargle=1.6.0=r45h785f33e_1
  - r-generics=0.1.4=r45hc72bb7e_1
  - r-ggplot2=4.0.0=r45h785f33e_0
  - r-ggrepel=0.9.6=r45h3697838_2
  - r-glue=1.8.0=r45h54b55ab_1
  - r-googledrive=2.1.2=r45hc72bb7e_1
  - r-googlesheets4=1.1.2=r45h785f33e_1
  - r-gtable=0.3.6=r45hc72bb7e_1
  - r-haven=2.5.5=r45h6d565e7_1
  - r-highr=0.11=r45hc72bb7e_2
  - r-hms=1.1.3=r45hc72bb7e_3
  - r-htmltools=0.5.8.1=r45h3697838_2
  - r-httr=1.4.7=r45hc72bb7e_2
  - r-ids=1.0.1=r45hc72bb7e_5
  - r-isoband=0.2.7=r45h3697838_4
  - r-jquerylib=0.1.4=r45hc72bb7e_4
  - r-jsonlite=2.0.0=r45h54b55ab_1
  - r-knitr=1.50=r45hc72bb7e_1
  - r-labeling=0.4.3=r45hc72bb7e_2
  - r-lattice=0.22_7=r45h54b55ab_1
  - r-lifecycle=1.0.4=r45hc72bb7e_2
  - r-lubridate=1.9.4=r45h54b55ab_1
  - r-magrittr=2.0.4=r45h54b55ab_0
  - r-mass=7.3_65=r45h54b55ab_0
  - r-matrix=1.7_4=r45h0e4624f_1
  - r-memoise=2.0.1=r45hc72bb7e_4
  - r-mgcv=1.9_3=r45h0e4624f_1
  - r-mime=0.13=r45h54b55ab_1
  - r-modelr=0.1.11=r45hc72bb7e_3
  - r-munsell=0.5.1=r45hc72bb7e_2
  - r-nlme=3.1_168=r45heaba542_1
  - r-openssl=2.3.3=r45h50f7d53_1
  - r-pillar=1.11.1=r45hc72bb7e_0
  - r-pkgconfig=2.0.3=r45hc72bb7e_5
  - r-prettyunits=1.2.0=r45hc72bb7e_2
  - r-processx=3.8.6=r45h54b55ab_1
  - r-progress=1.2.3=r45hc72bb7e_2
  - r-ps=1.9.1=r45h54b55ab_1
  - r-purrr=1.1.0=r45h54b55ab_1
  - r-r6=2.6.1=r45hc72bb7e_1
  - r-ragg=1.5.0=r45h9f1dc4d_1
  - r-rappdirs=0.3.3=r45h54b55ab_4
  - r-rcolorbrewer=1.1_3=r45h785f33e_4
  - r-rcpp=1.1.0=r45h3697838_1
  - r-readr=2.1.5=r45h3697838_2
  - r-readxl=1.4.5=r45h10e25cc_1
  - r-rematch=2.0.0=r45hc72bb7e_2
  - r-rematch2=2.1.2=r45hc72bb7e_5
  - r-reprex=2.1.1=r45hc72bb7e_2
  - r-rlang=1.1.6=r45h3697838_1
  - r-rmarkdown=2.29=r45hc72bb7e_1
  - r-rstudioapi=0.17.1=r45hc72bb7e_1
  - r-rvest=1.0.5=r45hc72bb7e_1
  - r-s7=0.2.0=r45h54b55ab_1
  - r-sass=0.4.10=r45h3697838_1
  - r-scales=1.4.0=r45hc72bb7e_1
  - r-selectr=0.4_2=r45hc72bb7e_5
  - r-stringi=1.8.7=r45h2dae267_1
  - r-stringr=1.5.2=r45h785f33e_1
  - r-sys=3.4.3=r45h54b55ab_1
  - r-systemfonts=1.2.3=r45h74f4acd_1
  - r-textshaping=1.0.3=r45h74f4acd_1
  - r-tibble=3.3.0=r45h54b55ab_1
  - r-tidyr=1.3.1=r45h3697838_2
  - r-tidyselect=1.2.1=r45hc72bb7e_2
  - r-tidyverse=2.0.0=r45h785f33e_3
  - r-timechange=0.3.0=r45h3697838_2
  - r-tinytex=0.57=r45hc72bb7e_1
  - r-tzdb=0.5.0=r45h3697838_2
  - r-utf8=1.2.6=r45h54b55ab_1
  - r-uuid=1.2_1=r45h54b55ab_1
  - r-vctrs=0.6.5=r45h3697838_2
  - r-viridislite=0.4.2=r45hc72bb7e_3
  - r-vroom=1.6.6=r45h3697838_0
  - r-withr=3.0.2=r45hc72bb7e_1
  - r-xfun=0.53=r45h3697838_1
  - r-xml2=1.4.0=r45hc6fd541_1
  - r-yaml=2.3.10=r45h54b55ab_1
  - readline=8.2=h8c095d6_2
  - sed=4.8=he412f7d_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tzdata=2025b=h78e105d_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: 
  /cfs/klemming/projects/snic/snic2020-6-222/Projects/Tconura/working/Andre/bin/miniforge3/envs/r-arena
