name: 
  reproduce_dada2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.6.3=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.45=default_hfdba357_104
  - bioconductor-biobase=2.62.0=r43ha9d7317_3
  - bioconductor-biocgenerics=0.48.1=r43hdfd78af_2
  - bioconductor-biocparallel=1.36.0=r43hf17093f_2
  - bioconductor-biostrings=2.70.1=r43ha9d7317_2
  - bioconductor-dada2=1.30.0=r43hf17093f_0
  - bioconductor-data-packages=20250625=hdfd78af_0
  - bioconductor-delayedarray=0.28.0=r43ha9d7317_2
  - bioconductor-genomeinfodb=1.38.1=r43hdfd78af_1
  - bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
  - bioconductor-genomicalignments=1.38.0=r43ha9d7317_1
  - bioconductor-genomicranges=1.54.1=r43ha9d7317_2
  - bioconductor-iranges=2.36.0=r43ha9d7317_2
  - bioconductor-matrixgenerics=1.14.0=r43hdfd78af_3
  - bioconductor-rhtslib=2.4.0=r43ha9d7317_2
  - bioconductor-rsamtools=2.18.0=r43hf17093f_2
  - bioconductor-s4arrays=1.2.0=r43ha9d7317_2
  - bioconductor-s4vectors=0.40.2=r43ha9d7317_2
  - bioconductor-shortread=1.60.0=r43hf17093f_1
  - bioconductor-sparsearray=1.2.2=r43ha9d7317_2
  - bioconductor-summarizedexperiment=1.32.0=r43hdfd78af_0
  - bioconductor-xvector=0.42.0=r43ha9d7317_2
  - bioconductor-zlibbioc=1.48.0=r43ha9d7317_2
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.17.0=h4e3cde8_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=h065a4ff_12
  - gfortran_impl_linux-64=15.2.0=h281d09f_12
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=hda75c37_12
  - harfbuzz=12.2.0=h15599e2_0
  - icu=75.1=he02047a_0
  - jq=1.5=0
  - kernel-headers_linux-64=4.18.0=he073ed8_8
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libcblas=3.11.0=2_h0358290_openblas
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_12
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_112
  - libgcc-ng=15.2.0=h69a702a_12
  - libgfortran=15.2.0=h69a702a_12
  - libgfortran-ng=15.2.0=h69a702a_12
  - libgfortran5=15.2.0=h68bc16d_12
  - libglib=2.86.2=h6548e54_1
  - libgomp=15.2.0=he0feb66_12
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=2_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.51=h421ea60_0
  - libsanitizer=15.2.0=h90f66d4_12
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_12
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_112
  - libstdcxx-ng=15.2.0=hdf11a46_12
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.14.0=h32b2ec7_102_cp314
  - python_abi=3.14=8_cp314
  - pyyaml=6.0.3=pyh7db6752_0
  - r-abind=1.4_5=r43hc72bb7e_1006
  - r-base=4.3.3=hc28aa72_21
  - r-bh=1.87.0_1=r43hc72bb7e_0
  - r-bitops=1.0_9=r43h2b5f3a1_0
  - r-cli=3.6.5=r43h93ab643_0
  - r-codetools=0.2_20=r43hc72bb7e_1
  - r-colorspace=2.1_1=r43hdb488b9_0
  - r-cpp11=0.5.2=r43h785f33e_1
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-deldir=2.0_4=r43hbcb9c34_1
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-farver=2.1.2=r43ha18555a_1
  - r-formatr=1.14=r43hc72bb7e_2
  - r-futile.logger=1.4.3=r43hc72bb7e_1006
  - r-futile.options=1.0.1=r43hc72bb7e_1005
  - r-ggplot2=3.5.2=r43hc72bb7e_0
  - r-glue=1.8.0=r43h2b5f3a1_0
  - r-gtable=0.3.6=r43hc72bb7e_0
  - r-hwriter=1.3.2.1=r43hc72bb7e_3
  - r-interp=1.1_6=r43ha36cffa_2
  - r-isoband=0.2.7=r43ha18555a_3
  - r-jpeg=0.1_11=r43hc5f1ce6_0
  - r-labeling=0.4.3=r43hc72bb7e_1
  - r-lambda.r=1.2.4=r43hc72bb7e_4
  - r-lattice=0.22_7=r43h2b5f3a1_0
  - r-latticeextra=0.6_30=r43hc72bb7e_3
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-mass=7.3_60.0.1=r43hb1dbf0f_1
  - r-matrix=1.6_5=r43he966344_1
  - r-matrixstats=1.5.0=r43h2b5f3a1_0
  - r-mgcv=1.9_3=r43h2ae2be5_0
  - r-munsell=0.5.1=r43hc72bb7e_1
  - r-nlme=3.1_168=r43hb67ce94_0
  - r-pillar=1.11.0=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-plyr=1.8.9=r43h3697838_2
  - r-png=0.1_8=r43h21f035c_2
  - r-r6=2.6.1=r43hc72bb7e_0
  - r-rcolorbrewer=1.1_3=r43h785f33e_3
  - r-rcpp=1.1.0=r43h93ab643_0
  - r-rcppeigen=0.3.4.0.2=r43hb79369c_0
  - r-rcppparallel=5.1.9=r43h93ab643_1
  - r-rcurl=1.98_1.17=r43hb79926e_0
  - r-reshape2=1.4.4=r43h3697838_5
  - r-rlang=1.1.6=r43h93ab643_0
  - r-scales=1.4.0=r43hc72bb7e_0
  - r-snow=0.4_4=r43hc72bb7e_3
  - r-stringi=1.8.7=r43h3c328a7_0
  - r-stringr=1.5.2=r43h785f33e_0
  - r-tibble=3.3.0=r43h2b5f3a1_0
  - r-utf8=1.2.6=r43h2b5f3a1_0
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-viridislite=0.4.2=r43hc72bb7e_2
  - r-withr=3.0.2=r43hc72bb7e_0
  - readline=8.2=h8c095d6_2
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.28=h4ee821c_8
  - tk=8.6.13=noxft_ha0e22de_103
  - tktable=2.10=h8d826fa_7
  - toml=0.10.2=pyhd8ed1ab_2
  - tomlkit=0.13.3=pyha770c72_0
  - tzdata=2025b=h78e105d_0
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - yq=3.4.3=pyhe01879c_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: 
  /cfs/klemming/projects/snic/snic2020-6-222/Projects/Tconura/working/Andre/bin/miniforge3/envs/slu_proj_R
